[domain]
n_size = 256
aspect_ratio = 1

[simulation]
num_gpus = 1
steps = 100000
print_interval = 1000
precision = "float"

[physics]
reynolds_number = 10000.0
u_max = 0.0256

[lattice]
stencil = "D3Q27"
reconstruction_order = 2

[cuda]
block_x = 32
block_y = 4
block_z = 4

[output]
vti = true
interval = 5000
