[domain]
n_size = 128
aspect_ratio = 1

[simulation]
num_gpus = 1
steps = 100000
print_interval = 5000
precision = "float"

[physics]
reynolds_number = 3200.0
u_max = 0.0256

[lattice]
stencil = "D3Q27"
reconstruction_order = 2

[output]
vti = false
interval = 5000
